- name: Mitm Setup
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False


  vars:
    user_name: "mitm"
    ok: "yes"

  vars_prompt:
    - name: "pubkey_path"
      prompt: "Enter path to your ssh pubkey"
      default: "~/.ssh/id_rsa.pub"
      private: no
    - name: "mitm_password"
      prompt: "Password of user mitm"
      private: yes
      default: "mitm"
    - name: "ssh_pwd_auth"
      prompt: "Deactivate ssh password auth? [yes/no]"
      private: no
      default: "yes"
    - name: "mitm_interface"
      prompt: "Mitm interface"
      private: no
      default: "ens10"
    - name: "own_ip"
      prompt: "Desired static ip"
      private: no
      default: "192.168.4.1"
    - name: "start_ip_range"
      prompt: "Start ip range"
      private: no
      default: "192.168.4.2"
    - name: "end_ip_range"
      prompt: "End ip range"
      private: no
      default: "192.168.4.250"


  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      tags: always
    - setup: # aka gather_facts

    - name: Get local ssh public key
      local_action: shell cat ~/.ssh/id_rsa.pub
      become: no
      register: pubkey_string



  roles:
    - { role: mitm, tags: ['mitm'] }
