
- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install mkpasswd
  apt:
    name: whois

- name: Install mitmproxy
  apt:
    name: mitmproxy

- name: Install tcpdump
  apt:
    name: tcpdump

- name: Install Iftop
  apt:
    name: iftop

- name: Install curl
  apt:
    name: curl

- name: Install dnsmasq
  apt:
    name: dnsmasq

- name: Install git
  apt:
    name: git

- name: Install wireshark
  apt:
    name: wireshark

- name: Install tshark
  apt:
    name: tshark

- debug:
    msg: "Mitm interface name: {{mitm_interface}}"

- debug:
    msg: "Your pubkey: {{pubkey_string.stdout}}"

- name: Activate pubkey auth
  lineinfile:
    line: "PubkeyAuthentication yes"
    path: /etc/ssh/sshd_config

- name: Hash password
  shell: mkpasswd --method=sha-512 "{{mitm_password}}"
  register: mitm_hash
  no_log: True

- name: Create user mitm
  user:
    create_home: yes
    groups:
      - sudo
      - wireshark
    name: "{{user_name}}"
    password: "{{mitm_hash.stdout}}"
    shell: /bin/bash
    update_password: always


- name: Set mitm users authorized key file
  authorized_key:
    user: "{{user_name}}"
    key: "{{pubkey_string.stdout}}"

- name: Deactivate ssh password auth
  lineinfile:
    line: "PasswordAuthentication no"
    path: /etc/ssh/sshd_config
  when: ssh_pwd_auth == "yes"

- name: Setting static ip
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto {{mitm_interface}}
      iface {{mitm_interface}} inet static
        address {{own_ip}}
        netmask 255.255.255.0

- name: Delete dnsmasq.conf
  file:
    path: /etc/dnsmasq.conf
    state: absent

- name: Setting up dhcp-server
  blockinfile:
    path: /etc/dnsmasq.conf
    create: yes
    block: |
      interface={{mitm_interface}}
      dhcp-range={{start_ip_range}},{{end_ip_range}},96h
      dhcp-option=option:router,{{own_ip}}
      dhcp-option=option:dns-server,{{own_ip}}

- name: Starting dhcp-server
  systemd:
    enabled: yes
    name: dnsmasq
    state: restarted

- name: Activate ip4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

# - name: Reroute http packets
#   iptables:
#     table: nat
#     action: append
#     chain: PREROUTING
#     in_interface: "{{mitm_interface}}"
#     protocol: tcp
#     destination_port: 80
#     jump: REDIRECT
#     to_ports: 8080

# - name: Reroute https packets
#   iptables:
#     table: nat
#     action: append
#     chain: PREROUTING
#     in_interface: "{{mitm_interface}}"
#     protocol: tcp
#     destination_port: 443
#     jump: REDIRECT
#     to_ports: 8080

# - name: Make iptables-persistent
#   apt:
#     name: iptables-persistent

- name: Checking out mitm scripts
  git:
    repo: "https://github.com/Luis-Hebendanz/network-mitm-scripts.git"
    dest: "/home/{{user_name}}/mitm-scripts"
    version: HEAD

- name: interface.conf
  lineinfile:
    path: "/home/{{user_name}}/mitm-scripts/input_interface.conf"
    create: yes
    line: "{{mitm_interface}}"

# create a share directory if it doesn't exist
- name: Create 'Share' directory
  file:
    path: /home/"{{user_name}}"/Share
    state: directory
    mode: 0755

- name: Create 'out' directory
  file:
    path: /home/"{{user_name}}"/mitm-scripts/out
    state: directory
    mode: 0755

- name: Reboot
  reboot:
